security:
    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser: 'auto'
    providers:
        users_in_memory:
            memory:
                users:
                    laszlo: { password: '$2y$13$yRXlCJKV9g3VerDxflD98uaEoXymW3KsXyHxP8MuB7/fHeZwKYoFW', roles: ['ROLE_ADMIN'] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            entry_point: form_login
            form_login: 
                login_path: security_login
                check_path: security_login
                enable_csrf: true
            logout:
                path: security_logout

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    access_control:
        - { path: ^/_login, roles: PUBLIC_ACCESS }
        - { path: ^/favicon.ico, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_ADMIN  }
