twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        systemHierarchy: '@App\Hierarchy\Schema\DefaultHierarchy'
        subSchemas: '@App\Hierarchy\Schema\SchemaList'

when@test:
    twig:
        strict_variables: true
